### PR TITLE
Fix: Use pascal case for issue property key

### LINKED ISSUE #1602: Use PascalCase case for knownissues
The content returned from the endpoint is camelCased, and we expect it to be PascalCased on the portal

### PR DESCRIPTION
**Pull request by Onokaev**
## Overview
Fixes #1602 

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

* How to test this PR
* Prefer bulleted description
* Start after checking out this branch
* Include any setup required, such as bundling scripts, restarting services, etc.
* Include test case, and expected output

### CODE REVIEW

File: GraphWebApi/Controllers/KnownIssuesController.cs [hunk 1]
```diff
@@ -42,7 +43,8 @@ public async Task<IActionResult> GetKnownIssues()
                                             _knownIssuesTraceProperties);
 
             List<KnownIssue> result = await _knownIssuesService.QueryBugsAsync();
-            return result == null ? NotFound() : Ok(result);
+
+            return result == null ? NotFound() : Ok(JsonConvert.SerializeObject(result));
```
Comment (andrueastman) [inline GraphWebApi/Controllers/KnownIssuesController.cs:47]: Because of this line in the project config
https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/ff1f170bd821fddf4f6800f537e01a8a9ec6c677/GraphWebApi/Startup.cs#L85

I suspect this file can remain unchanged after adding the property attributes and there is no need to call `JsonConvert.SerializeObject`. 
```suggestion
            return result == null ? NotFound() : Ok(result);
```

**Review by baywet — APPROVED** [review]

**Review by andrueastman — APPROVED** [review]
