### PR TITLE
Made snippet response write to stream asynchronous

### LINKED ISSUE #449: Some requests fail with 500 "Synchronous operations are disallowed"
Seems to be related to the length of the generated snippet - Objective-C seems more prone to this. Calling the live endpoint just returns the 500 without the callstack, so repro this against a local instance.

Repro:

```
POST https://localhost:44399/snippetgenerator?lang=Objective-C

POST /v1.0/users HTTP/1.1
Host: graph.microsoft.com
Content-Type: application/json

{
  "accountEnabled": true,
  "displayName": "Ensi Vasala",
  "mailNickname": "ensiv",
  "passwordProfile": {
    "forceChangePasswordNextSignIn": true,
    "password": "TZ%vTr24tCkp"
  },
  "usageLocation": "US",
  "userPrincipalName": "ensiv@contoso.com"
}
```

Response:

```
System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
   at Microsoft.AspNetCore.Server.IIS.Core.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNetCore.Server.IIS.Core.WrappingStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(String value)
   at GraphWebApi.Controllers.StringResult.ExecuteResultAsync(ActionContext context) in C:\Source\Repos\microsoft-graph-devx-api\GraphWebApi\Controllers\GraphExplorerSnippetsController.cs:line 75
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: */*
Accept-Encoding: gzip, deflate, br
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 356
Content-Type: application/http
Cookie: PHPSESSID=sue423b90vbh4qf2d9n2sjopd3
Host: localhost:44399
User-Agent: PostmanRuntime/7.26.8
Postman-Token: 19b1a784-4b3b-4209-b9d2-bedf948b39cc
```

Suggested fix:

In GraphExplorerSnippetsController.cs, in `ExecuteResultAsync` in the `StringResult` class, replace:

```
streamWriter.Write(this._value);
```

with:

```
await streamWriter.WriteAsync(this._value);
```

I've tested this locally and the request above goes through successfully and returns a snippet. 
[AB#8071](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8071)

### PR DESCRIPTION
**Pull request by jasonjoh**
Fixes #449

### CODE REVIEW

**Review by baywet — APPROVED** [review]

File: GraphWebApi/Controllers/GraphExplorerSnippetsController.cs [hunk 1]
```diff
@@ -72,7 +72,7 @@ public async Task ExecuteResultAsync(ActionContext context)
         {
             context.HttpContext.Response.ContentType = "text/plain";
             var streamWriter = new StreamWriter(context.HttpContext.Response.Body);
```
Comment (zengin) [inline GraphWebApi/Controllers/GraphExplorerSnippetsController.cs:74]: While at it, can we fix the disposal of the writer as well?

```suggestion
            using var streamWriter = new StreamWriter(context.HttpContext.Response.Body);
```

**Review by zengin — APPROVED** [review]

File: GraphWebApi/Controllers/GraphExplorerSnippetsController.cs (hunk 1 above)
Comment (jasonjoh) [reply GraphWebApi/Controllers/GraphExplorerSnippetsController.cs:74]: Sounds like a good idea to me.

**Review by zengin — APPROVED** [review]

File: GraphWebApi/Controllers/GraphExplorerSnippetsController.cs [hunk 2]
```diff
@@ -71,9 +71,9 @@ public StringResult(string value)
         public async Task ExecuteResultAsync(ActionContext context)
         {
             context.HttpContext.Response.ContentType = "text/plain";
-            var streamWriter = new StreamWriter(context.HttpContext.Response.Body);
-            streamWriter.Write(this._value);
+            using var streamWriter = new StreamWriter(context.HttpContext.Response.Body);
```
Comment (darrelmiller) [inline GraphWebApi/Controllers/GraphExplorerSnippetsController.cs:74]: I'm not sure if this using should be here.  Disposing the StreamWriter will close the stream which is the response stream that we didn't create.  It might be ok.  It might not.

Comment (zengin) [reply GraphWebApi/Controllers/GraphExplorerSnippetsController.cs:74]: I did not know about this rather interesting design choice by the `StreamWriter` implementation. It violates my understanding of memory ownership principles.

It is possibly OK given that we are flushing before disposing and we don't expect anyone else to write to the same stream but if there is any operation on that stream after this method, it can cause an `ObjectDisposedException`.
