### PR TITLE
Remove unnecessary clone when applying OpenAPI style

### LINKED ISSUE #1129: Missing RequestBodies in `/$ref` paths
**Describe the bug**
Request bodies are missing in `/$ref` paths.

**To Reproduce**
1. Go to https://graphexplorerapi.azurewebsites.net/$openapi?tags=groups.directoryObject&title=Users&openapiversion=3&style=Powershell&graphVersion=v1.0
2. Inspect `/groups/{group-id}/members/$ref` -> `Post` operation:
image
You'll see that `requestBody` is missing in the operation.

**Expected behavior**
RequestBodies should be present in `/$ref` paths.
``` diff
'/groups/{group-id}/members/$ref':
  post:
    tags:
      - groups.directoryObject
    summary: Create new navigation property ref to members for groups
    operationId: groups_CreateMembersByRef
    parameters:
      - name: group-id
        in: path
        description: 'key: id of group'
        required: true
        schema:
          type: string
        x-ms-docs-key-type: group
+   requestBody:
+    $ref: '#/components/requestBodies/refPostBody'
    responses:
      '204':
        description: Success
      4XX:
        $ref: '#/components/responses/error'
      5XX:
        $ref: '#/components/responses/error'
    x-ms-docs-operation-type: operation
```

### PR DESCRIPTION
**Pull request by millicentachieng**
## Overview
Fixes #1129 
Removes unnecessary clone when applying OpenAPI style

### CODE REVIEW

File: OpenAPIService/OpenApiService.cs [hunk 1]
```diff
@@ -603,23 +603,14 @@ public OpenApiDocument ApplyStyle(OpenApiStyle style, OpenApiDocument subsetOpen
 
             if (style == OpenApiStyle.GEAutocomplete)
             {
-                // Clone doc before making changes
-                subsetOpenApiDocument = CloneOpenApiDocument(subsetOpenApiDocument);
-
                 if(!includeRequestBody)
```
Comment (baywet) [inline OpenAPIService/OpenApiService.cs:606]: collapse this condition in the one above

**Review by baywet — CHANGES_REQUESTED** [review]

**Review by irvinesunday — APPROVED** [review]

**Review by baywet — APPROVED** [review]
